/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#6ffbbe",
        "on-background": "#131b2e",
        "on-primary-container": "#f4fffc",
        "surface-container-low": "#f2f3ff",
        "surface-dim": "#d2d9f4",
        "secondary-container": "#6cf8bb",
        "outline-variant": "#bcc9c6",
        "outline": "#6d7a77",
        "on-error-container": "#93000a",
        "primary-fixed": "#89f5e7",
        "primary": "#00685f",
        "on-secondary": "#ffffff",
        "inverse-surface": "#283044",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed-dim": "#6bd8cb",
        "surface-tint": "#006a61",
        "on-secondary-fixed-variant": "#005236",
        "surface": "#faf8ff",
        "on-surface-variant": "#3d4947",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-primary": "#ffffff",
        "secondary": "#006c49",
        "primary-container": "#008378",
        "inverse-primary": "#6bd8cb",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "background": "#faf8ff",
        "on-tertiary-fixed-variant": "#653e00",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#2a1700",
        "surface-container": "#eaedff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "tertiary-container": "#a36700",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#005049",
        "error-container": "#ffdad6",
        "on-secondary-container": "#00714d",
        "surface-container-highest": "#dae2fd",
        "tertiary": "#825100",
        "on-tertiary-container": "#fffbff"
      },
      "fontFamily": {
        "headline-lg": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "mono-data": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      }
    },
  },
  plugins: [],
}
